from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/teacher/', views.signup_teacher, name='signup_teacher'),
    path('signup/student/', views.signup_student, name='signup_student'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/approve/<int:user_id>/', views.approve_user, name='approve_user'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/edit/<int:course_id>/', views.course_edit, name='course_edit'),
    path('courses/delete/<int:course_id>/', views.course_delete, name='course_delete'),
    path('student/courses/', views.course_list_student, name='course_list_student'),
    path('student/courses/enroll/<int:course_id>/', views.enroll_course, name='enroll_course'),
    path('teacher/assignments/create/', views.assignment_create, name='assignment_create'),
    path('student/assignments/', views.assignment_list_student, name='assignment_list_student'),
    path('student/assignments/submit/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('teacher/assignments/<int:assignment_id>/submissions/', views.submission_list, name='submission_list'),
    path('teacher/submissions/<int:submission_id>/grade/', views.grade_submission, name='grade_submission'),
    path('student/grades/', views.student_grades, name='student_grades'),
    path('admin/grades/', views.all_grades, name='all_grades'),
    path('leave/request/', views.leave_request_create, name='leave_request_create'),
    path('leave/requests/', views.leave_requests, name='leave_requests'),
    path('admin/leave/requests/', views.admin_leave_requests, name='admin_leave_requests'),
    path('admin/leave/request/<int:leave_id>/<str:action>/', views.leave_request_review, name='leave_request_review'),
    path('announcements/create/', views.announcement_create, name='announcement_create'),
    path('announcements/', views.announcements_list, name='announcements_list'),
    path('messages/', views.conversation_list, name='conversation_list'),
    path('messages/start/<int:user_id>/', views.start_conversation, name='start_conversation'),
    path('messages/<int:conv_id>/', views.conversation_detail, name='conversation_detail'),
    path('messages/moderate/', views.moderate_messages, name='moderate_messages'),
    path('messages/delete/<int:msg_id>/', views.delete_message, name='delete_message'),
    path('messages/tag/<int:msg_id>/', views.tag_message, name='tag_message'),
    path('timetable/upload/', views.upload_timetable, name='upload_timetable'),
    path('timetable/view/', views.view_timetable, name='view_timetable'),
    path('grades/', views.grade_list, name='grade_list'),
    path('grades/create/', views.grade_create, name='grade_create'),
    path('grades/<int:pk>/edit/', views.grade_update, name='grade_update'),
    path('profile/', views.profile_view, name='profile'),
]
